
CREATE TABLE VAGAS (

	ID_VAGA INT PRIMARY KEY NOT NULL,
	TITULO VARCHAR(100) NOT NULL,
	EMPRESA VARCHAR(100) NOT NULL,
	SALARIO DECIMAL NOT NULL
	
);

CREATE TABLE CANDIDATAS (

	ID_CANDIDATA INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL
	
);

CREATE TABLE CANDIDATURAS (

	ID_CANDIDATURA INT PRIMARY KEY NOT NULL,
	DATA_ENVIO DATETIME NOT NULL,
	ID_VAGA INT NOT NULL,
	ID_CANDIDATA INT NOT NULL,
	
	FOREIGN KEY (ID_VAGA) REFERENCES VAGAS(ID_VAGA),
	FOREIGN KEY (ID_CANDIDATA) REFERENCES CANDIDATAS(ID_CANDIDATA)
	
);



